### ISSUE TITLE
Deprecated: preg_match() Error

### ISSUE THREAD

**Issue by pftnhr** [GiovanniSalmeri/yellow-link#2]
Hi Giovanni,

I'm getting this error message on page where I'm using a link text (`[link https://domain.tld "Nice link text"]`):
`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /www/htdocs/.../.../system/extensions/link.php on line 47`

**Comment by GiovanniSalmeri** [comment]
Hello! Thank you very much for spotting this, now it should be fixed. Can you confirm?

**Comment by pftnhr** [comment]
The error message is gone but now there is a line break in the output.

<img width="442" alt="Bildschirmfoto 2023-08-27 um 18 54 05" src="https://github.com/GiovanniSalmeri/yellow-link/assets/7520987/0f980c0a-13ee-45d8-9106-a441185693a0">

**Comment by GiovanniSalmeri** [comment]
Unfortunately I cannot reproduce the problem... Could you copy the exact markdown text which produces this output with those extra line breaks?

**Comment by pftnhr** [comment]
Of course:

``` markdown
[^1]: [link https://nova.app]
[^2]: [link https://panic.com]
[^3]: [link https://www.panic.com/transmit]
[^4]: [link why-yellow]
[^5]: [link https://sass-lang.com]
[^6]: [link https://brew.sh]
[^7]: [link https://emmet.io]
[^8]: [link https://github.com/beautify-web/js-beautify]
[^9]: [link https://beautifier.io]

```

**Comment by GiovanniSalmeri** [comment]
Should be fixed now, I had made a stupid change 😊 which I have now reverted.

**Comment by pftnhr** [comment]
Fantastic Giovanni, now everything fits.

Thank you very much!
